export const ActionTypes = {
  USER: {
    LOGIN: 'USER__LOGIN',
    LOGOUT: 'USER__LOGOUT',
  },

  CHAT_GPT: {
    LOADING: 'CHAT_GPT__LOADING',
    ME: 'CHAT_GPT__ME',
    GPT: 'CHAT_GPT__GPT',
  },

  TIKOP: {
    UPDATE: 'TIKOP_UPDATE',
  },

  GLOBLE_APP: {
    UPDATE: 'GLOBLE_APP:_UPDATE',
    SET_LOADING_TRUE: 'GLOBLE_APP:_SET_LOADING_TRUE',
    SET_LOADING_FALSE: 'GLOBLE_APP:_SET_LOADING_FALSE',
    SET_PURCHASED: 'GLOBLE_APP:_SET_PURCHASED',
    SET_SHOW_POPUP_BUY_PRO: 'GLOBLE_APP:_SET_SHOW_POPUP_BUY_PRO',
    UPDATE_QUOTES_THEME: 'GLOBLE_APP:_UPDATE_QUOTES_THEM',
    UPDATE_QUOTES_CATEGORY: 'GLOBLE_APP:_UPDATE_QUOTES_CATEGORY'
  },

  WEB_RTC: {
    UPDATE_MY_STREAM: 'WEB_RTC:_UPDATE_MY_STREAM',
  },

  MUSIC_PLAY: {
    PLAY_MUSIC: 'MUSIC_PLAY:_PLAY_MUSIC',
    SET_PLAYING_MUSIC: 'MUSIC_PLAY:_SET_PLAYING_MUSIC',
    CANCEL_MUSIC: 'MUSIC_PLAY:_CANCEL_MUSIC',
    SET_INFO_TIME: 'MUSIC_PLAY:_SET_INFO_TIME',
    PAUSE_OR_RESUME_MUSIC: 'MUSIC_PLAY:_PAUSE_OR_RESUME_MUSIC',
  },

  INDEXED_MUSICS: {
    SET_LIST_MUSICS: 'INDEXED_MUSICS:_SET_LIST_MUSICS',
    SET_CURRENT_INDEX: 'INDEXED_MUSICS:_SET_CURRENT_INDEX',
  },
}
