import {
  OPENAI_API_KEY,
  OPENAI_LENGH_HISTORY_TO_SAVE_MEMORY,
  START_PLATFORM,
  REVENUE_CAT_PUBLIC_API_KEY,
} from '@env';

const Env = {
  OPENAI_API_KEY,
  OPENAI_LENGH_HISTORY_TO_SAVE_MEMORY,
  START_PLATFORM,
  IS_START_PLATFORM_IOS: START_PLATFORM && START_PLATFORM === 'IOS',
  REVENUE_CAT_PUBLIC_API_KEY: 'appl_PoJDNMcxFFdUVWSDYjdMmfSTDUy',
}

export default Env;
